### ISSUE TITLE
Implement Vector and Matrix classes:

### ISSUE THREAD

**Issue by TheOneKevin** [TheOneKevin/JavaPhysicsSimulation#1]
- [x] Matrix * Matrix
- [ ] ~~Change to COLUMN MAJOR operations~~
- [x] Vector cross product, including 2 dimensions (in our case, z-component of 3d cross product)
- [x] For each operation, ensure there is a version of `c = VecN.opr(a, b)` (which modifies neither `a` nor `b`) and `a.opr(b)` (which modifies `a`).
- [x] Matrix transpose
- [x] Vector scalar product
Thank you! ~ Kevin

**Comment by Nova-Terra** [comment]
I will (hopefully) fix as many of the issues as possible today.

**Comment by TheOneKevin** [comment]
Thanks! I think this can be closed now.
